High difficulty
koroliana/Coursework1 pull request #1
Opened 2023-02-12 10:53 UTC by koroliana

Реализовала EmployeeBook через ArrayList. Мне показалось гораздо удобнее работать, когда с самого начала длина массива не ограничена.
Проверьте, пожалуйста.

2023-02-13 13:25 UTC, alekseykoshelev requested changes

2023-02-13 13:25 UTC, alekseykoshelev commented on src/Employee.java
> +        this.id=counterId +1;
Эти две строчки можно объединить. `this.id = counterId++`

2023-02-13 13:25 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +        Iterator<Employee> iterator = base.iterator();
Можно использовать метод `removeIf`. Раз уж тут ArrayList)
Там метод немного сложнее использовать, но зато сильно короче. Это не ошибка.

2023-02-13 13:25 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +    public ArrayList<Employee> getBase() {
Может лучше назвать как то `getEmployees`? А то не совсем понятно, что за base

2023-02-13 13:25 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +        Employee minSalaryEmployee = base.get(0);
А что если список пустой? Тут будет ошибка

2023-02-13 13:25 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +        return sum / base.size();
Если список пустой будет деление на 0

2023-02-13 13:25 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +            if (employee.getSalary() < minSalaryDepartmentEmployee.getSalary()) {
Эти два цикла можно объединить, просто добавить сюда еще проверку на отдел. Уйдет цикл и второй список.

2023-02-13 13:25 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +        ArrayList<Employee> departmentBase = new ArrayList<>();
Аналогичный момент.

2023-02-13 13:25 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +                departmentBase.add(employee);
Также можно избавится от двух циклов и списка. Заведи счетчик количества работников в данном отделе, а в конце метода раздели на него, только учти, что может быть 0 сотрудников в отделе.

2023-02-15 14:07 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +                departmentBase.add(employee);
Напишу пример кода как это может выглядеть
```
int empInDepartment = 0;
int sum = 0;
for (Employee employee : base) {
 if (employee.getDepartment() == department){
   sum = sum + employee.getSalary();
   empInDepartment++;
 } 
}
if (empInDepartment == 0) { 
   throw new RuntimeException("В " + department + " отделе нет сотрудников!");
}
return sum / (double) empInDepartment;
```

2023-02-15 14:09 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +        ArrayList<Employee> departmentBase = new ArrayList<>();
Тут можно применить похожую схему из примера ниже)

2023-02-15 16:01 UTC, koroliana commented on src/EmployeeBook.java
> +        ArrayList<Employee> departmentBase = new ArrayList<>();
@alekseykoshelev, внесла изменения. Очень жду проверки = )

2023-02-15 17:41 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +        if (departmentIsEmpty) {
Логика с флажком хорошая, но тут можно использовать переменную `maxDepartmentSalaryEmployee `
Проверить ее на `null`. Если она не равна `null`, то было хотя бы одно присваивание, а значит сотрудники есть в этом отделе.

2023-02-15 17:41 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +        if (departmentIsEmpty) {
Тут даже можно эту переменную также использовать для вычисления зарплаты, в таком случае надо просто добавить еще одно условие. Вот так
```
if (employee.getDepartment() == department && (maxDepartmentSalaryEmployee == null || employee.getSalary() > maxDepartmentSalaryEmployee.getSalary())){
```
В этом случае переменную `maxDepartmentSalary` можно будет убрать, но усложняется условие. Просто как еще один альтернативный вариант)

2023-02-15 17:41 UTC, alekseykoshelev commented on src/Employee.java
> +        else {
Блок else можно не делать, если выполнится условие, то выбросится эксепшен и код и так дальше не пойдет. Без else выглядит чуть лаконичнее)

2023-02-25 12:51 UTC, merged